#############################################################################
# Makefile for building: MagicTower.app/Contents/MacOS/MagicTower
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  MagicTower.pro
# Template: app
# Command: /usr/local/Cellar/qt/5.9.2/bin/qmake -o Makefile MagicTower.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
CXX           = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
DEFINES       = -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++ -F/usr/local/Cellar/qt/5.9.2/lib
QMAKE         = /usr/local/Cellar/qt/5.9.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Cellar/qt/5.9.2/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Cellar/qt/5.9.2/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MagicTower1.0.0
DISTDIR = /Users/armour/Magic-Tower-Qt/.tmp/MagicTower1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
LFLAGS        = -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.9.2/lib -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp moc_mainwindow.cpp \
		moc_cheat.cpp \
		moc_myview.cpp
OBJECTS       = main.o \
		moc_mainwindow.o \
		moc_cheat.o \
		moc_myview.o
DIST          = /usr/local/Cellar/qt/5.9.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++/qmake.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/lex.prf \
		MagicTower.pro mainwindow.h \
		cheat.h \
		database.h \
		equip.h \
		key.h \
		monster.h \
		myview.h \
		player.h \
		role.h main.cpp
QMAKE_TARGET  = MagicTower
DESTDIR       = 
TARGET        = MagicTower.app/Contents/MacOS/MagicTower

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d MagicTower.app/Contents/MacOS/ || mkdir -p MagicTower.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MagicTower.pro /usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt/5.9.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++/qmake.conf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.9.2/mkspecs/features/lex.prf \
		MagicTower.pro \
		/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/QtMultimedia.prl \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/QtSql.prl \
		/usr/local/Cellar/qt/5.9.2/lib/QtNetwork.framework/QtNetwork.prl \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile MagicTower.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64
/usr/local/Cellar/qt/5.9.2/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/g++-base.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_cgl_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++/qmake.conf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.9.2/mkspecs/features/lex.prf:
MagicTower.pro:
/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/QtMultimedia.prl:
/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/QtSql.prl:
/usr/local/Cellar/qt/5.9.2/lib/QtNetwork.framework/QtNetwork.prl:
/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MagicTower.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64

qmake_all: FORCE

MagicTower.app/Contents/PkgInfo: 
	@test -d MagicTower.app/Contents || mkdir -p MagicTower.app/Contents
	@$(DEL_FILE) MagicTower.app/Contents/PkgInfo
	@echo "APPL????" > MagicTower.app/Contents/PkgInfo
MagicTower.app/Contents/Resources/empty.lproj: 
	@test -d MagicTower.app/Contents/Resources || mkdir -p MagicTower.app/Contents/Resources
	@touch MagicTower.app/Contents/Resources/empty.lproj
	
MagicTower.app/Contents/Info.plist: 
	@test -d MagicTower.app/Contents || mkdir -p MagicTower.app/Contents
	@$(DEL_FILE) MagicTower.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,-301295753.armourg.MagicTower,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,MagicTower,g" -e "s,@LIBRARY@,MagicTower,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++/Info.plist.app >MagicTower.app/Contents/Info.plist

all: Makefile \
		MagicTower.app/Contents/PkgInfo \
		MagicTower.app/Contents/Resources/empty.lproj \
		MagicTower.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.9.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h cheat.h database.h equip.h key.h monster.h myview.h player.h role.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r MagicTower.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.9.2/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/usr/bin/g++ -pipe -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.9.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_cheat.cpp moc_myview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_cheat.cpp moc_myview.cpp
moc_mainwindow.cpp: myview.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		cheat.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers/QSound \
		/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers/qsound.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.2/bin/moc
	/usr/local/Cellar/qt/5.9.2/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++ -I/Users/armour/Magic-Tower-Qt -I/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.9.2/lib mainwindow.h -o moc_mainwindow.cpp

moc_cheat.cpp: /usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/qobject.h \
		cheat.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.2/bin/moc
	/usr/local/Cellar/qt/5.9.2/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++ -I/Users/armour/Magic-Tower-Qt -I/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.9.2/lib cheat.h -o moc_cheat.cpp

moc_myview.cpp: /usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		myview.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.2/bin/moc
	/usr/local/Cellar/qt/5.9.2/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.2/mkspecs/macx-g++ -I/Users/armour/Magic-Tower-Qt -I/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.9.2/lib myview.h -o moc_myview.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.cpp \
		mainwindow.h \
		myview.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		cheat.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers/QSound \
		/usr/local/Cellar/qt/5.9.2/lib/QtMultimedia.framework/Headers/qsound.h \
		database.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/QSqlDatabase \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/qsqldatabase.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/QSqlDriver \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/qsqldriver.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/QSqlError \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/qsqlerror.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/QSqlRecord \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/qsqlrecord.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/QSqlQuery \
		/usr/local/Cellar/qt/5.9.2/lib/QtSql.framework/Headers/qsqlquery.h \
		player.h \
		role.h \
		equip.h \
		monster.h \
		key.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/QtMath \
		/usr/local/Cellar/qt/5.9.2/lib/QtCore.framework/Headers/qmath.h \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.9.2/lib/QtWidgets.framework/Headers/qapplication.h \
		database.cpp \
		myview.cpp \
		/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.9.2/lib/QtGui.framework/Headers/qevent.h \
		player.cpp \
		cheat.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_cheat.o: moc_cheat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cheat.o moc_cheat.cpp

moc_myview.o: moc_myview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myview.o moc_myview.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

